name: test-clang-format

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.11
      with:
        source: '.'
        exclude: 'CMake'
        extensions: ''c,h,C,H,cpp,hpp,cc,hh,c++,h++,cxx,hxx'
        clangFormatVersion: 8
        style: file
